version: '3.1'
services:
  db:
    container_name: song_service
    image: postgres
    restart: always
    ports:
      - "5444:5432"
    environment:
      TZ: "Europe/Moscow"
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: song_service